---

- name: Install python kubernetes core pre-requisites
  ansible.builtin.pip:
    name:
      - pyyaml
      - kubernetes
      - jsonpatch

- name: Deploy Service Account with role and rolebinding to manage Cluster's nodes.
  kubernetes.core.k8s:
    state: present
    template:
      - path: '../templates/serviceaccount.yml.j2'

- name: Get Service Account detail
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ServiceAccount
    name: manage-node
    namespace: kube-system
  register: sa_manage_node

- name: Deploy Service Account secret
  kubernetes.core.k8s:
    state: present
    template:
      - path: '../templates/serviceaccountsecret.yml.j2'

- name: Pause for 20 second to let service account creation
  ansible.builtin.pause:
    seconds : 20

- name: Get Secret detail
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: manage-node
    namespace: kube-system
  register: sa_manage_node_secrets

- name: Add k3s_delete_node_token and k3s_delete_node_ca
  ansible.builtin.set_fact:
    k3s_delete_node_token: "{{ sa_manage_node_secrets['resources'][0]['data']['token'] | b64decode }}"
    k3s_delete_node_ca: "{{ sa_manage_node_secrets['resources'][0]['data']['ca.crt'] | b64decode }}"
