namespace: frantchenco
name: k3s
version: 1.0.0
readme: README.md
authors:
  - your name <example@domain.com>
description: K3s collection to install k3s
license_file: 'LICENSE'
tags: []
repository: https://github.com/Frantche/ansible_collection_k3s
documentation: http://docs.example.com
homepage: http://example.com
issues: https://github.com/Frantche/ansible_collection_k3s/issues
build_ignore: []
