---

- name: Copy K3s service file
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755
  notify: Restarted k3s

- name: Enable and check K3s service
  ansible.builtin.systemd:
    name: "k3s-node"
    daemon_reload: "yes"
    state: "started"
    enabled: "yes"
