---

- name: Install python kubernetes core pre-requisites
  become: true
  ansible.builtin.pip:
    name:
      - pyyaml
      - kubernetes

- name: Creates delete-node script location directory
  ansible.builtin.template:
    path: "{{ script_location }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0700

- name: Creates delete-node log directory
  ansible.builtin.template:
    path: "{{ log_location }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0700

- name: Copy K3s crt file
  ansible.builtin.template:
    src: "delete-node.crt.j2"
    dest: "{{ script_location }}/ca.crt"
    owner: "root"
    group: "root"
    mode: 0700

- name: Copy delete-node python script
  ansible.builtin.template:
    src: "delete-node.py.j2"
    dest: "{{ script_location }}/main.py"
    owner: "root"
    group: "root"
    mode: 0700

- name: Copy delete-node service
  ansible.builtin.template:
    src: "delete-node.service.j2"
    dest: "{{ systemd_dir }}/delete-node.service"
    owner: "root"
    group: "root"
    mode: 0700

- name: Ensure delete-node is started and enabled on shutdown.
  ansible.builtin.service:
    name: "delete-node"
    enabled: "yes"
    state: "started"
